version: '3'
services:
  rabbit:
    image: "rabbitmq:3.7.6"
    networks:
      - masqnet
    environment:
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_USER=guest
  
  s3:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_REGION: us-east-1
    command: minio server /data
    networks:
      - masqnet

  s3-test:
    image: "golang:1.10.3"
    volumes:
      - .go:/go
      - .:/app
      - .vagrant/root:/root
    environment:
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      AWS_REGION: us-east-1
    command: |
      /bin/bash -c "
        /app/wait-for-it.sh s3:9000 &&
        wget -N https://dl.minio.io/client/mc/release/linux-amd64/mc && 
        chmod +x mc && 
        ./mc config host add s3 http://s3:9000 minio minio123 &&
        ./mc mb mask &&
        cat /app/Readme.md | ./mc pipe mask/Readme.md &&
        ./mc cat mask/Readme.md
      "
    networks:
      - masqnet
  
  hdfs-test:
    image: sequenceiq/hadoop-docker:2.7.0
    volumes:
      - .:/app
    command: |
      /bin/bash -c "
        /etc/bootstrap.sh -bash &&
        /usr/local/hadoop/bin/hdfs dfsadmin -safemode leave &&
        cat /app/Readme.md | /usr/local/hadoop/bin/hdfs dfs -put - Readme.md &&
        /usr/local/hadoop/bin/hdfs dfs -cat Readme.md
      "
    networks:
      - masqnet

  acceptance:
    image: "golang:1.10.3"
    volumes:
      - .go:/go
      - .:/go/src/github.com/BBVA/masquerade
    working_dir: "/go/src/github.com/BBVA/masquerade/internal/features"
    command: "/go/src/github.com/BBVA/masquerade/wait-for-it.sh rabbit:5672 -- godog -t \"~@wip\" ."
    networks:
      - masqnet

networks:
  masqnet:
    driver: "bridge"